language: python

python:
    - 2.7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install python-dev libffi-dev libxml2-dev libxslt1-dev
    - sudo apt-get install libjpeg-dev

install:
    - python setup.py develop
    - pip install pytest pytest-cov coveralls

script:
    - py.test --cov=peepdf

after_success:
    - coveralls
